### PR TITLE
STABLE-6: OXT-858: Surfman spurious logs

### PR DESCRIPTION
**Pull request by eric-ch**
Silence debug logs and amend log-level to regular spurious logs.

### CODE REVIEW

**Comment by rossphilipson** [comment]
@eric-ch do you see this as a security related fix?

**Comment by eric-ch** [comment]
@rossphilipson These spurious logs (with the ones from QEMU) can easily trigger logrotate and have important logs removed. My point being loosing potentially important logs is a security related issue.

**Comment by richpersaud** [comment]
It's worth looking at the log files of a running OpenXT system.  Imagine being the production support engineer responsible for detecting anomalies.  This is a small step towards much-needed logfile cleanup to the standards of operational deployment.

This is a security issue, but there is no rule that says only security issues are allowed in 6.0.1 or other point releases.  Data corruption would be a non-security issue.  Broken functionality, e.g. inability to manage remotely, could be another.  If needed, we can document policy in a mailing list discussion and/or wiki page.

**Comment by rossphilipson** [comment]
Yes. I meant that this did not clearly fall under security related fixes or major bug fixes. It seemed it was just a cleanup of logging (which I agree is in need of some major help in general) so I questioned it - the answer was valid. A wiki that details what goes in a point release would be great; the working assumption is known (bad) bugs or security issues.

**Comment by eric-ch** [comment]
@richpersaud There is a general understanding around what is acceptable for micro release. It was mentioned during last month community call. I started a [thread on the ML](https://groups.google.com/d/msg/openxt/k-5WVG2c2xs/Bb-UhqM7CwAJ) and drafted a [wiki page](https://openxt.atlassian.net/wiki/display/~eric-ch/Version+meaning) on what I thought were the general assumptions.
Regarding your second point, bug-fixes & security features are basically what micro-releases were all about.

**Comment by jean-edouard** [comment]
Built here: http://158.69.127.133:8020/builders/openxt-custom/builds/224
LGTM, merging soon.

**Pull request merged**
