### PR TITLE
 Add proper support for "cloned" multi-monitor and panel fitting.

### PR DESCRIPTION
**Pull request by ktemkin**
This should make OpenXT behave much more nicely when a projector is attached.

### CODE REVIEW

**Comment by rossphilipson** [comment]
Maybe add a check on the return from malloc.

It looks good to me though Eric should sign off on it.

**Comment by ktemkin** [comment]
Agreed on the malloc-- I've adjusted that to provide a slightly more graceful failure path. I'll test the tweak more thoroughly tomorrow when I have a few more machines to test against.

**Comment by ktemkin** [comment]
Okay-- the tweaks didn't break anything in my simple tests. This can likely be merged pending Eric's approval.

**Comment by eric-ch** [comment]
LGTM

**Pull request merged**
